GET http://localhost:2000/api/systems HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IjRBTlVIWTk1RlJDek5QRksiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3hxZHB4aHFhbWhqZHd1aHNkcmx3LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI1NzU2MDVkMy05ZGE5LTQ0OGEtYjg2ZC1lYWM1OWRmYjIxMmYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzU1ODkyNjY2LCJpYXQiOjE3NTU4ODkwNjYsImVtYWlsIjoiYWxmcmVkb2NoaXZlbGEzQGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZGlzcGxheV9uYW1lIjoiRmVybmFuZG8gTWFudWVsIiwiZW1haWwiOiJhbGZyZWRvY2hpdmVsYTNAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNTc1NjA1ZDMtOWRhOS00NDhhLWI4NmQtZWFjNTlkZmIyMTJmIiwidXNlcm5hbWUiOiJGZXJuYW5kbyBNYW51ZWwifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc1NTg4OTA2NX1dLCJzZXNzaW9uX2lkIjoiOWJhNmUzMGMtZTcxZS00NjZlLTg3NjctMzU1MWRmNGY4YzIwIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.Tj_4lip5PJ8GQxQMvoIY4K631C9gO1dd18XI4P6NWxE

###
DELETE http://localhost:2000/api/systems/8af9fadc-82b0-46bf-876a-77e7302e2122 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IjRBTlVIWTk1RlJDek5QRksiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3hxZHB4aHFhbWhqZHd1aHNkcmx3LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI1NzU2MDVkMy05ZGE5LTQ0OGEtYjg2ZC1lYWM1OWRmYjIxMmYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzU1ODkyNjY2LCJpYXQiOjE3NTU4ODkwNjYsImVtYWlsIjoiYWxmcmVkb2NoaXZlbGEzQGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZGlzcGxheV9uYW1lIjoiRmVybmFuZG8gTWFudWVsIiwiZW1haWwiOiJhbGZyZWRvY2hpdmVsYTNAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNTc1NjA1ZDMtOWRhOS00NDhhLWI4NmQtZWFjNTlkZmIyMTJmIiwidXNlcm5hbWUiOiJGZXJuYW5kbyBNYW51ZWwifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc1NTg4OTA2NX1dLCJzZXNzaW9uX2lkIjoiOWJhNmUzMGMtZTcxZS00NjZlLTg3NjctMzU1MWRmNGY4YzIwIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.Tj_4lip5PJ8GQxQMvoIY4K631C9gO1dd18XI4P6NWxE


###

POST http://localhost:2000/api/systems HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IjRBTlVIWTk1RlJDek5QRksiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3hxZHB4aHFhbWhqZHd1aHNkcmx3LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI1NzU2MDVkMy05ZGE5LTQ0OGEtYjg2ZC1lYWM1OWRmYjIxMmYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzU1ODkyNjY2LCJpYXQiOjE3NTU4ODkwNjYsImVtYWlsIjoiYWxmcmVkb2NoaXZlbGEzQGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZGlzcGxheV9uYW1lIjoiRmVybmFuZG8gTWFudWVsIiwiZW1haWwiOiJhbGZyZWRvY2hpdmVsYTNAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNTc1NjA1ZDMtOWRhOS00NDhhLWI4NmQtZWFjNTlkZmIyMTJmIiwidXNlcm5hbWUiOiJGZXJuYW5kbyBNYW51ZWwifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc1NTg4OTA2NX1dLCJzZXNzaW9uX2lkIjoiOWJhNmUzMGMtZTcxZS00NjZlLTg3NjctMzU1MWRmNGY4YzIwIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.Tj_4lip5PJ8GQxQMvoIY4K631C9gO1dd18XI4P6NWxE
content-type: application/json

{
  "name":"RCS WEBSITE-CENTRAL",
  "id_type":"da87b9ce-43bf-4283-9431-3b9a58d31c41",
  "target":"https://www.google.com",
  "connection_type": "api", 
  "status":"up",
  "criticality_level":2,
  "sla_target":100,
  "check_interval":12
}

###

PATCH http://localhost:2000/api/systems/2919ad3b-4971-49ea-8850-a441d31ecf40 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IjRBTlVIWTk1RlJDek5QRksiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3hxZHB4aHFhbWhqZHd1aHNkcmx3LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI1NzU2MDVkMy05ZGE5LTQ0OGEtYjg2ZC1lYWM1OWRmYjIxMmYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzU1ODkyNjY2LCJpYXQiOjE3NTU4ODkwNjYsImVtYWlsIjoiYWxmcmVkb2NoaXZlbGEzQGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZGlzcGxheV9uYW1lIjoiRmVybmFuZG8gTWFudWVsIiwiZW1haWwiOiJhbGZyZWRvY2hpdmVsYTNAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNTc1NjA1ZDMtOWRhOS00NDhhLWI4NmQtZWFjNTlkZmIyMTJmIiwidXNlcm5hbWUiOiJGZXJuYW5kbyBNYW51ZWwifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc1NTg4OTA2NX1dLCJzZXNzaW9uX2lkIjoiOWJhNmUzMGMtZTcxZS00NjZlLTg3NjctMzU1MWRmNGY4YzIwIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.Tj_4lip5PJ8GQxQMvoIY4K631C9gO1dd18XI4P6NWxE
content-type: application/json

{ 
  "target":"www.google.com"
}


###
POST http://localhost:2000/api/auth/signin HTTP/1.1
content-type: application/json

{
    "email": "alfredochivela3@gmail.com",
    "password": "masculino"
}